# Generated by Django 3.1.7 on 2021-06-21 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitar',
            name='price',
            field=models.FloatField(default=5.0, help_text='Please enter the price of the guitar', null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1000000.0)], verbose_name='Price'),
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='type',
        ),
        migrations.AddField(
            model_name='guitar',
            name='type',
            field=models.ManyToManyField(help_text='Select a type for this guitar', to='guitars.Type'),
        ),
    ]
